<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] Threading + Exception Handling (2 Questions)
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:jonpryor%40vt.edu">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="013049.html">
   <LINK REL="Next"  HREF="013051.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] Threading + Exception Handling (2 Questions)
   </H1>
    <B>Jonathan Pryor
    </B> 
    <A HREF="mailto:jonpryor%40vt.edu"
       TITLE="[Mono-list] Threading + Exception Handling (2 Questions)">jonpryor@vt.edu
       </A><BR>
    <I>20 Mar 2003 09:47:09 -0500</I>
    <P><UL>
        <LI> Previous message: <A HREF="013049.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
        <LI> Next message: <A HREF="013051.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13050">[ date ]</a>
              <a href="thread.html#13050">[ thread ]</a>
              <a href="subject.html#13050">[ subject ]</a>
              <a href="author.html#13050">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>--=-z3WDgyELhBczgjoKeVBL
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

Oops.  Forgot to attach the UnhandledException sample.

 - Jon

On Thu, 2003-03-20 at 09:45, Jonathan Pryor wrote:
&gt;<i> It sounds like you want to have an exception generated in one thread
</I>&gt;<i> appear in another.  I don't think that's possible.  Exceptions are
</I>&gt;<i> relative to the thread they're generated from, and deal exclusively with
</I>&gt;<i> the thread of that stack.
</I>&gt;<i> 
</I>&gt;<i> However, there is a workaround, if I'm understanding you correctly.  You
</I>&gt;<i> could hook up the AppDomain.UnhandledException event to your first
</I>&gt;<i> thread, which would let you know if an exception was thrown from some
</I>&gt;<i> thread in your application and not caught.
</I>&gt;<i> 
</I>&gt;<i> In theory, you could use the UnhandledExceptionEventArgs information to
</I>&gt;<i> determine the type of the thrown exception, to ensure that you're
</I>&gt;<i> trapping the right errors.  Alas, this information appears to be null
</I>&gt;<i> for my build of mono (see attached sample program), but that might be
</I>&gt;<i> fixed by now.  Anyone else know for sure?
</I>&gt;<i> 
</I>&gt;<i> Regardless, your UnhandledException handler can set a variable which the
</I>&gt;<i> main thread checks.  If the variable is set, the main thread would throw
</I>&gt;<i> an exception, simulating the appearance of the thread moving from one
</I>&gt;<i> thread to another.
</I>&gt;<i> 
</I>&gt;<i> As for Thread.Abort, it should work as you expect.  Thread.Abort
</I>&gt;<i> generates an exception in the specified thread, not the calling thread
</I>&gt;<i> (unless they're the same), and that exception will have no effect on the
</I>&gt;<i> calling thread.  So Thread.Abort followed by a throw should work.
</I>&gt;<i> 
</I>&gt;<i> There is one problem, though.  Thread.Abort isn't implemented for mono
</I>&gt;<i> under Windows (it's a pthread under Windows problem; check the
</I>&gt;<i> archives), so this may not be an acceptable solution for you.
</I>&gt;<i> 
</I>&gt;<i>  - Jon
</I>&gt;<i> 
</I>&gt;<i> On Thu, 2003-03-20 at 08:51, Timothy Parez wrote:
</I>&gt;<i> &gt; Hello,
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt; I have class which creates another thread
</I>&gt;<i> &gt; now that other tread can throw a custom error, but
</I>&gt;<i> &gt; when this error is thrown I want the main thread of the class library
</I>&gt;<i> &gt; to receive this exception so that the client application which uses my
</I>&gt;<i> &gt; library get's this error and all execution of other code in my class
</I>&gt;<i> &gt; library is stopped.
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt;  //Code executed by the main thread:
</I>&gt;<i> &gt;   protected byte[] Query(byte[] sendData)
</I>&gt;<i> &gt;   {
</I>&gt;<i> &gt;    //Set all values
</I>&gt;<i> &gt;    data = sendData;
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt;    queryThread = new Thread(new ThreadStart(ExecuteQuery));
</I>&gt;<i> &gt;             
</I>&gt;<i> &gt;    //Start the query
</I>&gt;<i> &gt;    queryThread.Start();
</I>&gt;<i> &gt;    
</I>&gt;<i> &gt;    //Wait for the query to exit
</I>&gt;<i> &gt;    if (!queryThread.Join(timeout * 1000))
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     queryThread.Abort();
</I>&gt;<i> &gt;     throw new Exceptions.QueryTimeoutException(&quot;Query Timeout: &quot; +
</I>&gt;<i> &gt; timeout.ToString() + &quot; seconds&quot;);
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;    
</I>&gt;<i> &gt;    //Return the response, which is now saved in the local variable
</I>&gt;<i> &gt;    return queryResponse;
</I>&gt;<i> &gt;   }
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt; // Code executed by the queryThread
</I>&gt;<i> &gt;  private void ExecuteQuery()
</I>&gt;<i> &gt;   {
</I>&gt;<i> &gt;    UdpClient client = new UdpClient();
</I>&gt;<i> &gt;    //Connect to the server and send the query data
</I>&gt;<i> &gt;    try
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     client.Connect(ip,port);
</I>&gt;<i> &gt;     client.Send(data,data.Length);
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;    catch (Exception e)
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     client.Close();
</I>&gt;<i> &gt;     throw new Exceptions.InvalidHostException(&quot;Unknown host: &quot; +
</I>&gt;<i> &gt; ip,e);
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt;    //Listen for a response - This is the client side
</I>&gt;<i> &gt;    IPEndPoint serverIPEndPoint = new IPEndPoint(IPAddress.Any,0);
</I>&gt;<i> &gt;    
</I>&gt;<i> &gt;    //Receive the response
</I>&gt;<i> &gt;    try
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     queryResponse = client.Receive(ref serverIPEndPoint);
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;    catch (Exception e)
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     throw new Exceptions.ConnectionRefusedException(&quot;The connection
</I>&gt;<i> &gt; was refused by the remote host: &quot; + ip + &quot;:&quot; + port.ToString(),e);
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;    finally
</I>&gt;<i> &gt;    {
</I>&gt;<i> &gt;     client.Close();
</I>&gt;<i> &gt;    }
</I>&gt;<i> &gt;   }
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt; As you can see the ExecuteQuery() function can throw the
</I>&gt;<i> &gt; Exceptions.ConnectionRefusedException,
</I>&gt;<i> &gt; but my main thread never receives this error, so the execution of the
</I>&gt;<i> &gt; code in the main thread does not stop.
</I>&gt;<i> &gt; How can I fix this.
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt; I also have a second question: 
</I>&gt;<i> &gt;     queryThread.Abort();
</I>&gt;<i> &gt;     throw new Exceptions.QueryTimeoutException(&quot;Query Timeout: &quot; +
</I>&gt;<i> &gt; timeout.ToString() + &quot; seconds&quot;);
</I>&gt;<i> &gt; I abort the second thread, will the QueryTimeoutException still be
</I>&gt;<i> &gt; thrown ? (I hope so), or will the .Abort() cause an error
</I>&gt;<i> &gt; which will prevent from the QueryTimeoutException ever happening, in
</I>&gt;<i> &gt; that case how do I abort the second query and still throw the
</I>&gt;<i> &gt; QueryTimeoutException ?
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt;  
</I>&gt;<i> &gt; Thnx.
</I>&gt;<i> &gt; TP.
</I>&gt;<i> 
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;<i> <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>
--=-z3WDgyELhBczgjoKeVBL
Content-Disposition: attachment; filename=threading.cs
Content-Type: text/plain; name=threading.cs; charset=UTF-8
Content-Transfer-Encoding: 7bit

// What happens when a thread throws an uncaught exception?

using System;
using System.Threading;

class R {
  private static void Worker () {
    Console.WriteLine (&quot;Worker Thread: Working...&quot;);
    Thread.Sleep (500);
    Console.WriteLine (&quot;Worker Thread: Problem.&quot;);
    throw new Exception (&quot;Worker Thread Problem&quot;);
  }

  public static void Main () {
    Thread t = new Thread (new ThreadStart (Worker));
    Console.WriteLine (&quot;Main: Starting Worker&quot;);
    AppDomain.CurrentDomain.UnhandledException += 
      new UnhandledExceptionEventHandler (OnUnhandledException);
    t.Start ();
    t.Join ();
    Console.WriteLine (&quot;Main: Finished&quot;);
  }

  private static void OnUnhandledException (object sender, UnhandledExceptionEventArgs e)
  {
    Console.WriteLine (&quot;Unhandled Exception:&quot;);
    Console.WriteLine (&quot;  sender=&quot; + sender);
    Console.WriteLine (&quot;  e=&quot; + e);
    if (e != null) {
      Console.WriteLine (&quot;  e: &quot; + e);
      Console.WriteLine (&quot;  Exception: &quot; + e.ExceptionObject);
      Console.WriteLine (&quot;  IsTerminating: &quot; + e.IsTerminating);
    }
    else
      Console.WriteLine (&quot;  ** UnhandledExceptionEventArgs is null?!&quot;);

    Console.WriteLine (&quot;Generating New Exception&quot;);
    throw new Exception (&quot;In the right thread?&quot;);
  }
}


--=-z3WDgyELhBczgjoKeVBL--


</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="013049.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
	<LI> Next message: <A HREF="013051.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13050">[ date ]</a>
              <a href="thread.html#13050">[ thread ]</a>
              <a href="subject.html#13050">[ subject ]</a>
              <a href="author.html#13050">[ author ]</a>
         </LI>
       </UL>
</body></html>
