<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;Hello,&lt;br&gt;&lt;br&gt;&lt;/div&gt;I&nbsp;am&nbsp;trying&nbsp;to&nbsp;to&nbsp;use&nbsp;mono&nbsp;from&nbsp;python&nbsp;via&nbsp;pythonnet.&lt;br&gt;&lt;br&gt;&lt;/div&gt;My&nbsp;system:<br>
&lt;p&gt;&lt;strong&gt;Ubuntu&lt;/strong&gt;&lt;/p&gt;<br>
&lt;ul&gt;&lt;li&gt;Release&nbsp;16.04.1&nbsp;LTS&nbsp;(Xenial&nbsp;Xerus)&nbsp;32-bit&lt;/li&gt;&lt;li&gt;Kernel&nbsp;Linux&nbsp;4.1.19-v7+&nbsp;armv7l&lt;/li&gt;&lt;li&gt;MATE&nbsp;1.12.1&lt;/li&gt;&lt;/ul&gt;<br>
&lt;p&gt;&lt;strong&gt;Hardware&lt;/strong&gt;&lt;/p&gt;<br>
&lt;ul&gt;&lt;li&gt;Memory:&nbsp;925,8&nbsp;MiB&lt;/li&gt;&lt;li&gt;Processor:&nbsp;ARMv7&nbsp;Processor&nbsp;rev&nbsp;4&nbsp;(v7l)&nbsp;×&nbsp;4&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&lt;b&gt;Mono:&nbsp;&lt;/b&gt;mono-complete&nbsp;(4.2.4.4-0wheezy1)&lt;br&gt;&lt;/p&gt;<br>
&lt;strong&gt;&lt;/strong&gt;More&nbsp;information&nbsp;on&nbsp;the&nbsp;system&nbsp;and&nbsp;installed&nbsp;dependencies&nbsp;for&nbsp;pythonnet&nbsp;can&nbsp;be&nbsp;found&nbsp;in&nbsp;this&nbsp;thread:&nbsp;&lt;a&nbsp;href=&quot;https://github.com/pythonnet/pythonnet/issues/327&quot;&gt;https://github.com/pythonnet/pythonnet/issues/327&lt;/a&gt;&lt;br&gt;&lt;br&gt;&lt;/div&gt;The&nbsp;following&nbsp;small&nbsp;test&nbsp;script&nbsp;fails&nbsp;at&nbsp;the&nbsp;first&nbsp;step&nbsp;(importing&nbsp;the&nbsp;clr):&lt;br&gt;&lt;div&nbsp;style=&quot;margin-left:40px&quot;&gt;#!/usr/bin/env&nbsp;python3&lt;br&gt;&lt;br&gt;print(&#39;import&nbsp;clr&#39;)&lt;br&gt;import&nbsp;clr&lt;br&gt;print(&#39;clr&nbsp;imported&#39;)&lt;br&gt;&lt;br&gt;if&nbsp;__name__&nbsp;==&nbsp;&#39;__main__&#39;:&lt;br&gt;   &nbsp;print(&#39;main&#39;)&lt;br&gt;   &nbsp;exit(0)&lt;br&gt;&lt;br&gt;&lt;/div&gt;It&nbsp;gives&nbsp;the&nbsp;following&nbsp;traceback:&nbsp;&lt;br&gt;&lt;div&nbsp;style=&quot;margin-left:40px&quot;&gt;import&nbsp;clr&lt;br&gt;***&nbsp;Error&nbsp;in&nbsp;`python3.5&#39;:&nbsp;free():&nbsp;invalid&nbsp;pointer:&nbsp;0x75b92050&nbsp;***&lt;br&gt;Stacktrace:&lt;br&gt;&lt;br&gt; &nbsp;at&nbsp;&lt;unknown&gt;&nbsp;&lt;0xffffffff&gt;&lt;br&gt; &nbsp;at&nbsp;(wrapper&nbsp;managed-to-native)&nbsp;Python.Runtime.Runtime.Py_Initialize&nbsp;()&nbsp;&lt;0xffffffff&gt;&lt;br&gt; &nbsp;at&nbsp;Python.Runtime.Runtime.Initialize&nbsp;()&nbsp;&lt;0x0002f&gt;&lt;br&gt; &nbsp;at&nbsp;Python.Runtime.PythonEngine.Initialize&nbsp;()&nbsp;&lt;0x00093&gt;&lt;br&gt; &nbsp;at&nbsp;Python.Runtime.PythonEngine.InitExt&nbsp;()&nbsp;&lt;0x0002f&gt;&lt;br&gt; &nbsp;at&nbsp;(wrapper&nbsp;runtime-invoke)&nbsp;&lt;Module&gt;.runtime_invoke_intptr&nbsp;(object,intptr,intptr,intptr)&nbsp;&lt;0xffffffff&gt;&lt;br&gt;&lt;br&gt;Native&nbsp;stacktrace:&lt;br&gt;&lt;br&gt;&lt;br&gt;Debug&nbsp;info&nbsp;from&nbsp;gdb:&lt;br&gt;&lt;br&gt;[New&nbsp;LWP&nbsp;1901]&lt;br&gt;[Thread&nbsp;debugging&nbsp;using&nbsp;libthread_db&nbsp;enabled]&lt;br&gt;Using&nbsp;host&nbsp;libthread_db&nbsp;library&nbsp;&quot;/lib/arm-linux-gnueabihf/libthread_db.so.1&quot;.&lt;br&gt;0x76f23454&nbsp;in&nbsp;__libc_do_syscall&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt; &nbsp;Id  &nbsp;Target&nbsp;Id        &nbsp;Frame&nbsp;&lt;br&gt;*&nbsp;1   &nbsp;Thread&nbsp;0x76f8a300&nbsp;(LWP&nbsp;1900)&nbsp;&quot;python3.5&quot;&nbsp;0x76f23454&nbsp;in&nbsp;__libc_do_syscall&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt; &nbsp;2   &nbsp;Thread&nbsp;0x76250470&nbsp;(LWP&nbsp;1901)&nbsp;&quot;Finalizer&quot;&nbsp;0x76f23454&nbsp;in&nbsp;__libc_do_syscall&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;&lt;br&gt;Thread&nbsp;2&nbsp;(Thread&nbsp;0x76250470&nbsp;(LWP&nbsp;1901)):&lt;br&gt;#0 &nbsp;0x76f23454&nbsp;in&nbsp;__libc_do_syscall&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;#1 &nbsp;0x76f20834&nbsp;in&nbsp;do_futex_wait.constprop&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;#2 &nbsp;0x76f20916&nbsp;in&nbsp;__new_sem_wait_slow.constprop.0&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;#3 &nbsp;0x767dae84&nbsp;in&nbsp;mono_sem_wait&nbsp;()&nbsp;from&nbsp;/usr/lib/libmonoboehm-2.0.so.1&lt;br&gt;#4 &nbsp;0x767a89a0&nbsp;in&nbsp;??&nbsp;()&nbsp;from&nbsp;/usr/lib/libmonoboehm-2.0.so.1&lt;br&gt;Backtrace&nbsp;stopped:&nbsp;previous&nbsp;frame&nbsp;identical&nbsp;to&nbsp;this&nbsp;frame&nbsp;(corrupt&nbsp;stack?)&lt;br&gt;&lt;br&gt;Thread&nbsp;1&nbsp;(Thread&nbsp;0x76f8a300&nbsp;(LWP&nbsp;1900)):&lt;br&gt;#0 &nbsp;0x76f23454&nbsp;in&nbsp;__libc_do_syscall&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;#1 &nbsp;0x76f2232a&nbsp;in&nbsp;waitpid&nbsp;()&nbsp;from&nbsp;/lib/arm-linux-gnueabihf/libpthread.so.0&lt;br&gt;#2 &nbsp;0x767122bc&nbsp;in&nbsp;??&nbsp;()&nbsp;from&nbsp;/usr/lib/libmonoboehm-2.0.so.1&lt;br&gt;Backtrace&nbsp;stopped:&nbsp;previous&nbsp;frame&nbsp;identical&nbsp;to&nbsp;this&nbsp;frame&nbsp;(corrupt&nbsp;stack?)&lt;br&gt;&lt;br&gt;=================================================================&lt;br&gt;Got&nbsp;a&nbsp;SIGABRT&nbsp;while&nbsp;executing&nbsp;native&nbsp;code.&nbsp;This&nbsp;usually&nbsp;indicates&lt;br&gt;a&nbsp;fatal&nbsp;error&nbsp;in&nbsp;the&nbsp;mono&nbsp;runtime&nbsp;or&nbsp;one&nbsp;of&nbsp;the&nbsp;native&nbsp;libraries&nbsp;&lt;br&gt;used&nbsp;by&nbsp;your&nbsp;application.&lt;br&gt;=================================================================&lt;br&gt;&lt;br&gt;Aborted&nbsp;(core&nbsp;dumped)&lt;br&gt;&lt;/div&gt;&lt;br&gt;&lt;/div&gt;My&nbsp;debugging&nbsp;skills&nbsp;are&nbsp;very&nbsp;poor,&nbsp;anyway,&nbsp;I&nbsp;tried&nbsp;to&nbsp;use&nbsp;valgrind&nbsp;to&nbsp;get&nbsp;perhaps&nbsp;a&nbsp;better&nbsp;idea.&nbsp;The&nbsp;output:&lt;br&gt;&lt;div&nbsp;style=&quot;margin-left:40px&quot;&gt;==2813==&nbsp;Memcheck,&nbsp;a&nbsp;memory&nbsp;error&nbsp;detector&lt;br&gt;==2813==&nbsp;Copyright&nbsp;(C)&nbsp;2002-2015,&nbsp;and&nbsp;GNU&nbsp;GPL&#39;d,&nbsp;by&nbsp;Julian&nbsp;Seward&nbsp;et&nbsp;al.&lt;br&gt;==2813==&nbsp;Using&nbsp;Valgrind-3.11.0&nbsp;and&nbsp;LibVEX;&nbsp;rerun&nbsp;with&nbsp;-h&nbsp;for&nbsp;copyright&nbsp;info&lt;br&gt;==2813==&nbsp;Command:&nbsp;python3.5&nbsp;pythonnet_test.py&lt;br&gt;==2813==&nbsp;&lt;br&gt;disInstr(arm):&nbsp;unhandled&nbsp;instruction:&nbsp;0xF1010200&lt;br&gt;                &nbsp;cond=15(0xF)&nbsp;27:20=16(0x10)&nbsp;4:4=0&nbsp;3:0=0(0x0)&lt;br&gt;==2813==&nbsp;valgrind:&nbsp;Unrecognised&nbsp;instruction&nbsp;at&nbsp;address&nbsp;0x48596f4.&lt;br&gt;==2813==   &nbsp;at&nbsp;0x48596F4:&nbsp;???&nbsp;(in&nbsp;/usr/lib/arm-linux-gnueabihf/libarmmem.so)&lt;br&gt;==2813==&nbsp;Your&nbsp;program&nbsp;just&nbsp;tried&nbsp;to&nbsp;execute&nbsp;an&nbsp;instruction&nbsp;that&nbsp;Valgrind&lt;br&gt;==2813==&nbsp;did&nbsp;not&nbsp;recognise. &nbsp;There&nbsp;are&nbsp;two&nbsp;possible&nbsp;reasons&nbsp;for&nbsp;this.&lt;br&gt;==2813==&nbsp;1.&nbsp;Your&nbsp;program&nbsp;has&nbsp;a&nbsp;bug&nbsp;and&nbsp;erroneously&nbsp;jumped&nbsp;to&nbsp;a&nbsp;non-code&lt;br&gt;==2813==   &nbsp;location. &nbsp;If&nbsp;you&nbsp;are&nbsp;running&nbsp;Memcheck&nbsp;and&nbsp;you&nbsp;just&nbsp;saw&nbsp;a&lt;br&gt;==2813==   &nbsp;warning&nbsp;about&nbsp;a&nbsp;bad&nbsp;jump,&nbsp;it&#39;s&nbsp;probably&nbsp;your&nbsp;program&#39;s&nbsp;fault.&lt;br&gt;==2813==&nbsp;2.&nbsp;The&nbsp;instruction&nbsp;is&nbsp;legitimate&nbsp;but&nbsp;Valgrind&nbsp;doesn&#39;t&nbsp;handle&nbsp;it,&lt;br&gt;==2813==   &nbsp;i.e.&nbsp;it&#39;s&nbsp;Valgrind&#39;s&nbsp;fault. &nbsp;If&nbsp;you&nbsp;think&nbsp;this&nbsp;is&nbsp;the&nbsp;case&nbsp;or&lt;br&gt;==2813==   &nbsp;you&nbsp;are&nbsp;not&nbsp;sure,&nbsp;please&nbsp;let&nbsp;us&nbsp;know&nbsp;and&nbsp;we&#39;ll&nbsp;try&nbsp;to&nbsp;fix&nbsp;it.&lt;br&gt;==2813==&nbsp;Either&nbsp;way,&nbsp;Valgrind&nbsp;will&nbsp;now&nbsp;raise&nbsp;a&nbsp;SIGILL&nbsp;signal&nbsp;which&nbsp;will&lt;br&gt;==2813==&nbsp;probably&nbsp;kill&nbsp;your&nbsp;program.&lt;br&gt;==2813==&nbsp;&lt;br&gt;==2813==&nbsp;Process&nbsp;terminating&nbsp;with&nbsp;default&nbsp;action&nbsp;of&nbsp;signal&nbsp;4&nbsp;(SIGILL)&lt;br&gt;==2813== &nbsp;Illegal&nbsp;opcode&nbsp;at&nbsp;address&nbsp;0x48596F4&lt;br&gt;==2813==   &nbsp;at&nbsp;0x48596F4:&nbsp;???&nbsp;(in&nbsp;/usr/lib/arm-linux-gnueabihf/libarmmem.so)&lt;br&gt;==2813==&nbsp;&lt;br&gt;==2813==&nbsp;HEAP&nbsp;SUMMARY:&lt;br&gt;==2813==    &nbsp;in&nbsp;use&nbsp;at&nbsp;exit:&nbsp;1,088&nbsp;bytes&nbsp;in&nbsp;10&nbsp;blocks&lt;br&gt;==2813==  &nbsp;total&nbsp;heap&nbsp;usage:&nbsp;62&nbsp;allocs,&nbsp;52&nbsp;frees,&nbsp;5,692&nbsp;bytes&nbsp;allocated&lt;br&gt;==2813==&nbsp;&lt;br&gt;==2813==&nbsp;LEAK&nbsp;SUMMARY:&lt;br&gt;==2813==   &nbsp;definitely&nbsp;lost:&nbsp;0&nbsp;bytes&nbsp;in&nbsp;0&nbsp;blocks&lt;br&gt;==2813==   &nbsp;indirectly&nbsp;lost:&nbsp;0&nbsp;bytes&nbsp;in&nbsp;0&nbsp;blocks&lt;br&gt;==2813==     &nbsp;possibly&nbsp;lost:&nbsp;0&nbsp;bytes&nbsp;in&nbsp;0&nbsp;blocks&lt;br&gt;==2813==   &nbsp;still&nbsp;reachable:&nbsp;1,088&nbsp;bytes&nbsp;in&nbsp;10&nbsp;blocks&lt;br&gt;==2813==        &nbsp;suppressed:&nbsp;0&nbsp;bytes&nbsp;in&nbsp;0&nbsp;blocks&lt;br&gt;==2813==&nbsp;Rerun&nbsp;with&nbsp;--leak-check=full&nbsp;to&nbsp;see&nbsp;details&nbsp;of&nbsp;leaked&nbsp;memory&lt;br&gt;==2813==&nbsp;&lt;br&gt;==2813==&nbsp;For&nbsp;counts&nbsp;of&nbsp;detected&nbsp;and&nbsp;suppressed&nbsp;errors,&nbsp;rerun&nbsp;with:&nbsp;-v&lt;br&gt;==2813==&nbsp;ERROR&nbsp;SUMMARY:&nbsp;0&nbsp;errors&nbsp;from&nbsp;0&nbsp;contexts&nbsp;(suppressed:&nbsp;0&nbsp;from&nbsp;0)&lt;br&gt;Illegal&nbsp;instruction&nbsp;(core&nbsp;dumped)&lt;br&gt;&lt;/div&gt;&lt;br&gt;&lt;/div&gt;Both&nbsp;the&nbsp;traceback&nbsp;from&nbsp;python&nbsp;and&nbsp;the&nbsp;output&nbsp;of&nbsp;valgrind&nbsp;are&nbsp;beyond&nbsp;my&nbsp;comprehension.&lt;br&gt;&lt;br&gt;&lt;/div&gt;Has&nbsp;anyone&nbsp;have&nbsp;an&nbsp;idea,&nbsp;what&nbsp;is&nbsp;wrong,&nbsp;and&nbsp;how&nbsp;to&nbsp;fix&nbsp;it?&lt;br&gt;&lt;div&gt;&lt;div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Thanks&lt;br&gt;&lt;/div&gt;&lt;div&gt;Daniel&lt;br&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;<br>

</tt>
