<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-dev] NullReferenceException thrown inside catch
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-dev%5D%20NullReferenceException%20thrown%20inside%20catch&In-Reply-To=eck8ke%24jkp%241%40sea.gmane.org">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="020069.html">
   <LINK REL="Next"  HREF="020071.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-dev] NullReferenceException thrown inside catch</H1>
    <B>Robert Jordan</B> 
    <A HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-dev%5D%20NullReferenceException%20thrown%20inside%20catch&In-Reply-To=eck8ke%24jkp%241%40sea.gmane.org"
       TITLE="[Mono-dev] NullReferenceException thrown inside catch">robertj at gmx.net
       </A><BR>
    <I>Thu Aug 24 09:20:15 EDT 2006</I>
    <P><UL>
        <LI>Previous message: <A HREF="020069.html">[Mono-dev] NullReferenceException thrown inside catch
</A></li>
        <LI>Next message: <A HREF="020071.html">[Mono-dev] NullReferenceException thrown inside catch
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#20070">[ date ]</a>
              <a href="thread.html#20070">[ thread ]</a>
              <a href="subject.html#20070">[ subject ]</a>
              <a href="author.html#20070">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Robert Jordan wrote:
&gt;<i> Hi,
</I>&gt;<i> 
</I>&gt;<i> Janne Rantala wrote:
</I>&gt;&gt;<i> I found out that when NullReferenceException is thrown inside catch
</I>&gt;&gt;<i> clause in embedded environment, Mono crashes. Normally when method is
</I>&gt;&gt;<i> invoked with mono_runtime_invoke, exceptions are stored in MonoObject
</I>&gt;&gt;<i> but somehow this does not happen in this case.
</I>&gt;&gt;<i> This happened when I tried to print out message from InnerException
</I>&gt;&gt;<i> which didn't exist.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Here is the code, without that Console.WriteLine it works ok
</I>&gt;&gt;<i> (exception is stored in MonoObject).
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> Here is another simple sample:
</I>&gt;<i> 
</I>&gt;<i> public void CrashMe ()
</I>&gt;<i> {
</I>&gt;<i> 	null.Equals (null);
</I>&gt;<i> }
</I>&gt;<i> 
</I>&gt;<i> 
</I>&gt;<i> It seems that a &quot;true&quot; SIGSEGV (generated by native JIT code)
</I>&gt;<i> cannot be caught by mono_runtime_invoke ().
</I>&gt;<i> 
</I>&gt;<i> Please file a bug, if no one objects (it could be by design).
</I>
Oh, it's a Windows problem. I cannot reproduce it under Linux.

Robert


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="020069.html">[Mono-dev] NullReferenceException thrown inside catch
</A></li>
	<LI>Next message: <A HREF="020071.html">[Mono-dev] NullReferenceException thrown inside catch
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#20070">[ date ]</a>
              <a href="thread.html#20070">[ thread ]</a>
              <a href="subject.html#20070">[ subject ]</a>
              <a href="author.html#20070">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-devel-list">More information about the Mono-devel-list
mailing list</a><br>
</body></html>
