<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] Throwing custom exceptions in .NET Remoting
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-list%40lists.ximian.com?Subject=%5BMono-list%5D%20%3D%3Futf-8%3Fq%3FThrowing_custom_exceptions_in_%3D2ENET_Remoti%3F%3D%0A%09%3D%3Futf-8%3Fq%3Fng%3F%3D&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="039068.html">
   <LINK REL="Next"  HREF="039063.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] Throwing custom exceptions in .NET Remoting</H1>
    <B>paszczi</B> 
    <A HREF="mailto:mono-list%40lists.ximian.com?Subject=%5BMono-list%5D%20%3D%3Futf-8%3Fq%3FThrowing_custom_exceptions_in_%3D2ENET_Remoti%3F%3D%0A%09%3D%3Futf-8%3Fq%3Fng%3F%3D&In-Reply-To="
       TITLE="[Mono-list] Throwing custom exceptions in .NET Remoting">paszczi at go2.pl
       </A><BR>
    <I>Wed Jul 16 16:31:46 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="039068.html">[Mono-list] out of threads?
</A></li>
        <LI>Next message: <A HREF="039063.html">[Mono-list] Some problems when porting a .NET application from	Windows to Linux.
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39062">[ date ]</a>
              <a href="thread.html#39062">[ thread ]</a>
              <a href="subject.html#39062">[ subject ]</a>
              <a href="author.html#39062">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I have a problem when it comes to throwing custom exception in server-side sink. After some validation I want to throw ValidationException this comes to the client as RemotingException with no InnerException and only by the contents of StackTrace I'm able to determine which exception was thrown. This is very ... stupid solution but what I'm doing now is I'm catching such exceptions in client-side sink and rethrow is as appropriate exception. However this becomes impossible when calling methods asynchronously. So I have a simple solution - can I rethrow custom exception instead of RemotingException in the server sink?


Best regards,
Maciej Paszta
</PRE>




<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="039068.html">[Mono-list] out of threads?
</A></li>
	<LI>Next message: <A HREF="039063.html">[Mono-list] Some problems when porting a .NET application from	Windows to Linux.
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39062">[ date ]</a>
              <a href="thread.html#39062">[ thread ]</a>
              <a href="subject.html#39062">[ subject ]</a>
              <a href="author.html#39062">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-list">More information about the Mono-list
mailing list</a><br>
</body></html>
