<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] mono_runtime_invoke not catching exceptions?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-list%40lists.ximian.com?Subject=Re%3A%20%5BMono-list%5D%20mono_runtime_invoke%20not%20catching%20exceptions%3F&In-Reply-To=%3Cji0vm8%24ev9%241%40dough.gmane.org%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="048259.html">
   <LINK REL="Next"  HREF="048264.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] mono_runtime_invoke not catching exceptions?</H1>
    <B>Robert Jordan</B> 
    <A HREF="mailto:mono-list%40lists.ximian.com?Subject=Re%3A%20%5BMono-list%5D%20mono_runtime_invoke%20not%20catching%20exceptions%3F&In-Reply-To=%3Cji0vm8%24ev9%241%40dough.gmane.org%3E"
       TITLE="[Mono-list] mono_runtime_invoke not catching exceptions?">robertj at gmx.net
       </A><BR>
    <I>Tue Feb 21 20:43:13 UTC 2012</I>
    <P><UL>
        <LI>Previous message: <A HREF="048259.html">[Mono-list] mono_runtime_invoke not catching exceptions?
</A></li>
        <LI>Next message: <A HREF="048264.html">[Mono-list] mono_runtime_invoke not catching exceptions?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48263">[ date ]</a>
              <a href="thread.html#48263">[ thread ]</a>
              <a href="subject.html#48263">[ subject ]</a>
              <a href="author.html#48263">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 21.02.2012 18:36, efontana wrote:
&gt;<i> I'm using Embedded mono, I created a small test program who's method I can
</I>&gt;<i> call and as a test
</I>&gt;<i> I had that method do a throw new Exception(&quot;Catch this in C++&quot;);
</I>&gt;<i>
</I>&gt;<i> I passed in a MonoObject* exception = NULL; as the last argument to
</I>&gt;<i>
</I>&gt;<i> mono_runtime_invoke, the method returns, however exception is still NULL.
</I>&gt;<i> it's not being caught?
</I>&gt;<i>
</I>&gt;<i> Am I missing something,
</I>
I can't reproduce it with an official build or with a cygwin-compiled
Mono. Are you building Mono with Visual Studio?

Robert

</PRE>













<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="048259.html">[Mono-list] mono_runtime_invoke not catching exceptions?
</A></li>
	<LI>Next message: <A HREF="048264.html">[Mono-list] mono_runtime_invoke not catching exceptions?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48263">[ date ]</a>
              <a href="thread.html#48263">[ thread ]</a>
              <a href="subject.html#48263">[ subject ]</a>
              <a href="author.html#48263">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-list">More information about the Mono-list
mailing list</a><br>
</body></html>
