<tt>
I&nbsp;just&nbsp;upgraded&nbsp;to&nbsp;2.10&nbsp;and&nbsp;am&nbsp;getting&nbsp;strange&nbsp;behavior&nbsp;that&nbsp;I&nbsp;wasn&amp;#39;t&nbsp;seeing&nbsp;in&nbsp;2.8.1&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;call&nbsp;VerifyAccess&nbsp;in&nbsp;my&nbsp;code&nbsp;which&nbsp;is&nbsp;the&nbsp;method&nbsp;in&nbsp;the&nbsp;Dispatcher&nbsp;class&nbsp;that&nbsp;will&nbsp;compare&nbsp;the&nbsp;calling&nbsp;thread&nbsp;with&nbsp;the&nbsp;thread&nbsp;that&nbsp;the&nbsp;dispatcher&nbsp;was&nbsp;created&nbsp;on,&nbsp;if&nbsp;they&nbsp;differ&nbsp;it&nbsp;will&nbsp;throw&nbsp;an&nbsp;exception.&nbsp;In&nbsp;2.8.1&nbsp;it&nbsp;seemed&nbsp;that&nbsp;the&nbsp;Dispatcher&nbsp;object&nbsp;was&nbsp;always&nbsp;null&nbsp;so&nbsp;I&nbsp;never&nbsp;called&nbsp;these&nbsp;methods. &lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;In&nbsp;2.10&nbsp;it&nbsp;seems&nbsp;the&nbsp;Dispatcher&nbsp;is&nbsp;no&nbsp;longer&nbsp;null&nbsp;so&nbsp;I&nbsp;am&nbsp;making&nbsp;it&nbsp;into&nbsp;my&nbsp;calls&nbsp;to&nbsp;VerifyAccess&nbsp;and&nbsp;it&nbsp;is&nbsp;throwing&nbsp;an&nbsp;exception:&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;System.InvalidOperationException:&nbsp;&amp;quot;The&nbsp;calling&nbsp;thread&nbsp;is&nbsp;not&nbsp;the&nbsp;same&nbsp;as&nbsp;the&nbsp;creation&nbsp;thread&amp;quot;&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;a&nbsp;few&nbsp;things&nbsp;that&nbsp;are&nbsp;strange&nbsp;about&nbsp;this:&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;Prior&nbsp;to&nbsp;calling&nbsp;verify&nbsp;access&nbsp;I&nbsp;am&nbsp;doing&nbsp;some&nbsp;sanity&nbsp;checks &lt;/div&gt;&lt;div&gt;1.&nbsp;Dispatcher&nbsp;is&nbsp;not&nbsp;null&lt;/div&gt;&lt;div&gt;2.&nbsp;It&amp;#39;s&nbsp;hash&nbsp;code&nbsp;matches&nbsp;the&nbsp;Thread.CurrentThreads&nbsp;hash&nbsp;code&lt;/div&gt;<br>
&lt;div&gt;3.&nbsp;Dispatcher.Thread&nbsp;==&nbsp;Thread.CurrentThread evaluates true&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;4.&nbsp;Looking&nbsp;at&nbsp;the&nbsp;code&nbsp;from&nbsp;the&nbsp;2.10&nbsp;branch&nbsp;for&nbsp;dispatcher&nbsp;this&nbsp;doesn&amp;#39;t&nbsp;appear&nbsp;to&nbsp;be&nbsp;the&nbsp;error&nbsp;text&nbsp;that&nbsp;should&nbsp;be&nbsp;thrown&nbsp;so&nbsp;I&nbsp;assume&nbsp;something&nbsp;else&nbsp;is&nbsp;going&nbsp;on&nbsp;here.&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;That&nbsp;seems&nbsp;to&nbsp;tell&nbsp;me&nbsp;that&nbsp;they&nbsp;are&nbsp;in&nbsp;fact&nbsp;the&nbsp;same&nbsp;thread&nbsp;and&nbsp;the&nbsp;exception&nbsp;should&nbsp;NOT&nbsp;be&nbsp;thrown.&nbsp;Since&nbsp;the&nbsp;error&nbsp;message&nbsp;doesn&amp;#39;t&nbsp;seem&nbsp;correct&nbsp;I&nbsp;assume&nbsp;something&nbsp;else&nbsp;is&nbsp;going&nbsp;on&nbsp;here&nbsp;that&nbsp;I&nbsp;don&amp;#39;t&nbsp;understand.&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Any&nbsp;ideas?&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;div&gt;&lt;br&gt;--&nbsp;&lt;br&gt;Brad&nbsp;Cunningham&lt;br&gt;Microsoft&nbsp;MVP:&nbsp;C#&lt;br&gt;&lt;br&gt;&lt;a&nbsp;href=&quot;http://blog.bradcunningham.net&quot;&gt;http://blog.bradcunningham.net&lt;/a&gt;&lt;br&gt;<br>
<br>
&lt;/div&gt;&lt;/div&gt;<br>

</tt>
