<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 61608][Nor] New - RecvFrom_internal throws exception on connected socket
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:bugzilla-daemon%40bugzilla.ximian.com">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="018708.html">
   <LINK REL="Next"  HREF="018710.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 61608][Nor] New - RecvFrom_internal throws exception on connected socket
   </H1>
    <B>bugzilla-daemon@bugzilla.ximian.com
    </B> 
    <A HREF="mailto:bugzilla-daemon%40bugzilla.ximian.com"
       TITLE="[Mono-bugs] [Bug 61608][Nor] New - RecvFrom_internal throws exception on connected socket">bugzilla-daemon@bugzilla.ximian.com
       </A><BR>
    <I>Thu, 15 Jul 2004 11:49:08 -0400 (EDT)</I>
    <P><UL>
        <LI> Previous message: <A HREF="018708.html">[Mono-bugs] [Bug 61582][Nor] Changed - GetNamedDataSlot is not thread-safe
</A></li>
        <LI> Next message: <A HREF="018710.html">[Mono-bugs] [Bug 61608][Nor] Changed - RecvFrom_internal throws exception on connected socket
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18709">[ date ]</a>
              <a href="thread.html#18709">[ thread ]</a>
              <a href="subject.html#18709">[ subject ]</a>
              <a href="author.html#18709">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Please do not reply to this email- if you want to comment on the bug, go to the
URL shown below and enter your comments there.

Changed by <A HREF="mailto:dev@6wardlaw.freeserve.co.uk.">dev@6wardlaw.freeserve.co.uk.</A>

<A HREF="http://bugzilla.ximian.com/show_bug.cgi?id=61608">http://bugzilla.ximian.com/show_bug.cgi?id=61608</A>

--- shadow/61608	2004-07-15 11:49:08.000000000 -0400
+++ shadow/61608.tmp.11648	2004-07-15 11:49:08.000000000 -0400
@@ -0,0 +1,66 @@
+Bug#: 61608
+Product: Mono: Runtime
+Version: unspecified
+OS: Red Hat 9.0
+OS Details: Fedora Core 1.0
+Status: NEW   
+Resolution: 
+Severity: Unknown
+Priority: Normal
+Component: misc
+AssignedTo: <A HREF="mailto:mono-bugs@ximian.com">mono-bugs@ximian.com</A>                            
+ReportedBy: <A HREF="mailto:dev@6wardlaw.freeserve.co.uk">dev@6wardlaw.freeserve.co.uk</A>               
+QAContact: <A HREF="mailto:mono-bugs@ximian.com">mono-bugs@ximian.com</A>
+TargetMilestone: ---
+URL: 
+Cc: 
+Summary: RecvFrom_internal throws exception on connected socket
+
+Description of Problem:
+
+When 'RecvFrom_internal' is called on a connected connection-oriented 
+socket, a 'System.SystemException' is thrown by the run-time.
+
+The exception is actually thrown in the 'create_object_from_sockaddr' 
+function where a check is made on the socket address length.
+
+Because the stack returns a socket address length of 0 ( correctly as 
+this is a connecte socket ) this check fails and the exception is thrown.
+
+Steps to reproduce the problem:
+1. Create a stream socket and connect it to a remote endpoint.
+2. Call ReceiveFrom on the local socket
+3. Send some data from the remote endpoint over the connection.
+
+Actual Results:
+
+Exception: System.SystemException
+Message: A system exception has occurred.
+in (unmanaged) (wrapper managed-to-native) 
+System.Net.Sockets.Socket:RecvFrom_internal (intptr,byte
+[],int,int,System.Net.Sockets.SocketFlags,System.Net.SocketAddress&amp;,int&amp;)
+in &lt;0x00004&gt; (wrapper managed-to-native) 
+System.Net.Sockets.Socket:RecvFrom_internal (intptr,byte
+[],int,int,System.Net.Sockets.SocketFlags,System.Net.SocketAddress&amp;,int&amp;)
+in &lt;0x00050&gt; System.Net.Sockets.Socket:ReceiveFrom_nochecks (byte
+[],int,int,System.Net.Sockets.SocketFlags,System.Net.EndPoint&amp;)
+in &lt;0x00102&gt; System.Net.Sockets.Socket:ReceiveFrom (byte
+[],int,int,System.Net.Sockets.SocketFlags,System.Net.EndPoint&amp;)
+in &lt;0x00123&gt; Codestuff.Core.Network.NetworkConnection:OnDataAvailable 
+(System.Net.Sockets.Socket,Codestuff.Core.Network.SocketEvent,object)
+
+Expected Results:
+
+No exception
+
+
+How often does this happen? 
+
+Always
+
+
+Additional Information:
+
+Suggest a fix to the runtime code which is attached. Note that this 
+should also be applied in conjunction with a fix to the Socket managed 
+class to prevent a NullReferenceException being thrown ( see attached )

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="018708.html">[Mono-bugs] [Bug 61582][Nor] Changed - GetNamedDataSlot is not thread-safe
</A></li>
	<LI> Next message: <A HREF="018710.html">[Mono-bugs] [Bug 61608][Nor] Changed - RecvFrom_internal throws exception on connected socket
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18709">[ date ]</a>
              <a href="thread.html#18709">[ thread ]</a>
              <a href="subject.html#18709">[ subject ]</a>
              <a href="author.html#18709">[ author ]</a>
         </LI>
       </UL>
</body></html>
