<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] exceptions are not thrown from ThreadPool'ed thread
 objects?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:marianoa%40itcsoluciones.com">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="023871.html">
   <LINK REL="Next"  HREF="023861.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] exceptions are not thrown from ThreadPool'ed thread
 objects?
   </H1>
    <B>Mariano Alarcon
    </B> 
    <A HREF="mailto:marianoa%40itcsoluciones.com"
       TITLE="[Mono-list] exceptions are not thrown from ThreadPool'ed thread
 objects?">marianoa@itcsoluciones.com
       </A><BR>
    <I>Tue, 19 Oct 2004 14:47:12 -0300</I>
    <P><UL>
        <LI> Previous message: <A HREF="023871.html">[Mono-list] exceptions are not thrown from ThreadPool'ed
 thread objects?
</A></li>
        <LI> Next message: <A HREF="023861.html">[Mono-list] Using the Microsoft class libraries with the Mono CLR
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23872">[ date ]</a>
              <a href="thread.html#23872">[ thread ]</a>
              <a href="subject.html#23872">[ subject ]</a>
              <a href="author.html#23872">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I see the same results (exception not thrown) in my gentoo with mono 
1.0. But when I take the mcs binary and run it on my winxp with ms.net 
1.1 the exception is caught by the main thread. I don't know what the 
correct behavior should be, but there is certainly something different 
between the two implementations.

gennady wexler wrote:

&gt;<i>how about mono? can you see it not working when run under mono? including
</I>&gt;<i>1.1.1? then we need to bug this. would be nice if someone on monodev can
</I>&gt;<i>comment on this. is this an unsupported scenario?
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>On 10/19/04 5:09 AM, &quot;Mariano Alarcon&quot; &lt;<A HREF="mailto:marianoa@itcsoluciones.com">marianoa@itcsoluciones.com</A>&gt; wrote:
</I>&gt;<i>
</I>&gt;<i>  
</I>&gt;<i>
</I>&gt;&gt;<i>It works as expected with ms.net without having to uncomment anything.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>gennady wexler wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>    
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>has anyone noticed this problem? that is if you have a ThreadPool'ed thread
</I>&gt;&gt;&gt;<i>object created, any exception thrown inside of that thread will not be
</I>&gt;&gt;&gt;<i>rethrown up at all. I ran into this accidentally while developing some
</I>&gt;&gt;&gt;<i>performance code..
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>here's an example, could someone please try this with .net compiler/runtime?
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>if you just compile and run it, the exception in _ThreadProc does not get
</I>&gt;&gt;&gt;<i>thrown.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>now, if you uncomment regular thread definition below &quot;ThreadPool&quot; - you
</I>&gt;&gt;&gt;<i>will get &quot;exception 2&quot; get thrown.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>any ideas? is this expected? I hope not...
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>using System;
</I>&gt;&gt;&gt;<i>using System.Threading;
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>public class main {
</I>&gt;&gt;&gt;<i>       static void Main() {
</I>&gt;&gt;&gt;<i>               // this will not throw exception 1 (seems to be a bug?)
</I>&gt;&gt;&gt;<i>               ThreadPool.UnsafeQueueUserWorkItem(new
</I>&gt;&gt;&gt;<i>                       WaitCallback(_ThreadProc), null);
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>               // uncomment this to thrown exception 2 (as expected)
</I>&gt;&gt;&gt;<i>               // new Thread(new ThreadStart(_ThreadProc2)).Start();
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>               Thread.Sleep(90000);
</I>&gt;&gt;&gt;<i>       }
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>       private static void _ThreadProc(Object state) {
</I>&gt;&gt;&gt;<i>               throw new Exception(&quot;exception 1&quot;);
</I>&gt;&gt;&gt;<i>       }
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>       private static void _ThreadProc2() {
</I>&gt;&gt;&gt;<i>               throw new Exception(&quot;exception 2&quot;);
</I>&gt;&gt;&gt;<i>       }
</I>&gt;&gt;&gt;<i>}
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>_______________________________________________
</I>&gt;&gt;&gt;<i>Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;&gt;&gt;<i><A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> 
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>      
</I>&gt;&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>  
</I>&gt;<i>
</I>
-- 
Mariano Alarcón
ITC Soluciones


</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="023871.html">[Mono-list] exceptions are not thrown from ThreadPool'ed
 thread objects?
</A></li>
	<LI> Next message: <A HREF="023861.html">[Mono-list] Using the Microsoft class libraries with the Mono CLR
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23872">[ date ]</a>
              <a href="thread.html#23872">[ thread ]</a>
              <a href="subject.html#23872">[ subject ]</a>
              <a href="author.html#23872">[ author ]</a>
         </LI>
       </UL>
</body></html>
