<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 458947] New: SEGFAULT when from within a generic class a method of another class is called , wich throws an eception
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20458947%5D%20New%3A%20SEGFAULT%20when%20from%20within%20a%20generic%0A%20class%20a%20method%20of%20another%20class%20is%20called%20%2C%20wich%20throws%20an%20eception&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="083367.html">
   <LINK REL="Next"  HREF="083365.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 458947] New: SEGFAULT when from within a generic class a method of another class is called , wich throws an eception</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20458947%5D%20New%3A%20SEGFAULT%20when%20from%20within%20a%20generic%0A%20class%20a%20method%20of%20another%20class%20is%20called%20%2C%20wich%20throws%20an%20eception&In-Reply-To="
       TITLE="[Mono-bugs] [Bug 458947] New: SEGFAULT when from within a generic class a method of another class is called , wich throws an eception">bugzilla_noreply at novell.com
       </A><BR>
    <I>Sat Dec 13 23:41:05 EST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="083367.html">[Mono-bugs] [Bug 458942] Enum.GetName returns incorrect value
</A></li>
        <LI>Next message: <A HREF="083365.html">[Mono-bugs] [Bug 458947] SEGFAULT when from within a generic class a method of another class is called , wich throws an eception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#83362">[ date ]</a>
              <a href="thread.html#83362">[ thread ]</a>
              <a href="subject.html#83362">[ subject ]</a>
              <a href="author.html#83362">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE><A HREF="https://bugzilla.novell.com/show_bug.cgi?id=458947">https://bugzilla.novell.com/show_bug.cgi?id=458947</A>


           Summary: SEGFAULT when from within a generic class a method of
                    another class is called, wich throws an eception
           Product: Mono: Runtime
           Version: 2.2.x
          Platform: x86-64
        OS/Version: Linux
            Status: NEW
          Severity: Major
          Priority: P5 - None
         Component: generics
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono at e-tobi.net</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
          Found By: ---


Created an attachment (id=259952)
 --&gt; (<A HREF="https://bugzilla.novell.com/attachment.cgi?id=259952">https://bugzilla.novell.com/attachment.cgi?id=259952</A>)
Fixes the bug by setting the generic sharing mode to CORLIB again

This bug hit me when porting StructureMap to Mono and it was really hard to
find, because there was no usable stack trace and the method that caused the
problem was buried deep in the call hierarchy and in the end even was some
emitted code.

But I manged to put this into a very simple test case:


public class TestClass&lt;T&gt;
{
    public void Test()
    {
        try
        {
            new SomeClass().ThrowAnException();
        }
        catch
        {
        }
    }
}

public class SomeClass
{
    public void ThrowAnException()
    {
        throw new Exception(&quot;Something went wrong&quot;);
    }
}

public class MainClass
{
    public static void Main()
    {
        new TestClass&lt;string&gt;().Test();
    }
}

What happens here is, that a generic class calls another classes method, which
throws an exception that causes a SEGFAULT in the runtime (see below).

This happens ONLY if:

a) The calling class is generic
b) The method that throws is on another class
c) try / catch is used in the generic class

The bug is in 2.2 as well as in the trunk. It was introduced with revision
114108: &quot;class.c (mono_class_generic_sharing_enabled): Experimentally change
the default generic sharing mode to 'all'&quot;.

Reverting this commit (which is just a one-liner, see the attached patch) fixes
the problem.

Here's the runtime error, when you execute the above code:

[mono-trunk] /tmp/structuremap/build @ mono --debug ./test2.exe
Stacktrace:


Native stacktrace:

        mono [0x47da70]
        mono [0x4adaed]
        /lib/libpthread.so.0 [0x7f0c9bce5a80]
        mono [0x47cbb2]
        mono [0x47caa5]
        mono(mono_amd64_throw_exception+0x139) [0x4ae959]
        [0x41849b36]

Debug info from gdb:

[Thread debugging using libthread_db enabled]
[New Thread 0x7f0c9c9be720 (LWP 8790)]
[New Thread 0x41a58950 (LWP 8792)]
[New Thread 0x41b99950 (LWP 8791)]
0x00007f0c9b7cd269 in syscall () from /lib/libc.so.6
  3 Thread 0x41b99950 (LWP 8791)  0x00007f0c9bce50e1 in nanosleep () from
/lib/libpthread.so.0
  2 Thread 0x41a58950 (LWP 8792)  0x00007f0c9bce3bd1 in sem_wait () from
/lib/libpthread.so.0
  1 Thread 0x7f0c9c9be720 (LWP 8790)  0x00007f0c9b7cd269 in syscall () from
/lib/libc.so.6

Thread 3 (Thread 0x41b99950 (LWP 8791)):
#0  0x00007f0c9bce50e1 in nanosleep () from /lib/libpthread.so.0
#1  0x00000000005566b2 in collection_thread (unused=&lt;value optimized out&gt;) at
collection.c:34
#2  0x00007f0c9bcddfc7 in start_thread () from /lib/libpthread.so.0
#3  0x00007f0c9b7d05ad in clone () from /lib/libc.so.6
#4  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x41a58950 (LWP 8792)):
#0  0x00007f0c9bce3bd1 in sem_wait () from /lib/libpthread.so.0
#1  0x000000000052707a in finalizer_thread (unused=&lt;value optimized out&gt;) at
gc.c:928
#2  0x0000000000510613 in start_wrapper (data=&lt;value optimized out&gt;) at
threads.c:620
#3  0x00000000005587eb in thread_start_routine (args=0x21302f8) at
threads.c:279
#4  0x000000000056e9c2 in GC_start_routine (arg=0x7f0c9c869e70) at
pthread_support.c:1382
#5  0x00007f0c9bcddfc7 in start_thread () from /lib/libpthread.so.0
#6  0x00007f0c9b7d05ad in clone () from /lib/libc.so.6
#7  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f0c9c9be720 (LWP 8790)):
#0  0x00007f0c9b7cd269 in syscall () from /lib/libc.so.6
#1  0x000000000047db72 in mono_handle_native_sigsegv (signal=7, ctx=&lt;value
optimized out&gt;) at mini-exceptions.c:1406
#2  0x00000000004adaed in mono_arch_handle_altstack_exception
(sigctx=0x7f0c9c863c40, fault_addr=&lt;value optimized out&gt;, stack_ovf=0) at
exceptions-amd64.c:888
#3  &lt;signal handler called&gt;
#4  0x000000000047cbb2 in mono_handle_exception_internal (ctx=0x7fffa49df1e0,
obj=0x7f0c9c80bde0, original_ip=&lt;value optimized out&gt;, test_only=1,
out_filter_idx=0x7fffa49df28c)
    at mini-exceptions.c:755
#5  0x000000000047caa5 in mono_handle_exception_internal (ctx=0x7fffa49df2d0,
obj=0x7f0c9c80bde0, original_ip=0x41b8655c, test_only=0, out_filter_idx=0x0) at
mini-exceptions.c:863
#6  0x00000000004ae959 in mono_amd64_throw_exception (dummy1=&lt;value optimized
out&gt;, dummy2=&lt;value optimized out&gt;, dummy3=&lt;value optimized out&gt;, dummy4=&lt;value
optimized out&gt;, 
    dummy5=&lt;value optimized out&gt;, dummy6=&lt;value optimized out&gt;,
exc=0x7f0c9c80bde0, rip=1102603612, rsp=140735955203056, rbx=0,
rbp=140735955203136, r12=34576784, r13=0, 
    r14=139692142398464, r15=0, rdi=139692142018016, rsi=139692142042960,
rax=139692142018016, rcx=1102602688, rdx=0, rethrow=0) at
exceptions-amd64.c:348
#7  0x0000000041849b36 in ?? ()
#8  0x00007f0c9c80bde0 in ?? ()
#9  0x0000000041b8655c in ?? ()
#10 0x00007fffa49df3f0 in ?? ()
#11 0x0000000000000000 in ?? ()
#0  0x00007f0c9b7cd269 in syscall () from /lib/libc.so.6

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================


-- 
Configure bugmail: <A HREF="https://bugzilla.novell.com/userprefs.cgi?tab=email">https://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
You are the assignee for the bug.
</PRE>













































































































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="083367.html">[Mono-bugs] [Bug 458942] Enum.GetName returns incorrect value
</A></li>
	<LI>Next message: <A HREF="083365.html">[Mono-bugs] [Bug 458947] SEGFAULT when from within a generic class a method of another class is called , wich throws an eception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#83362">[ date ]</a>
              <a href="thread.html#83362">[ thread ]</a>
              <a href="subject.html#83362">[ subject ]</a>
              <a href="author.html#83362">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
