<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;Hey&nbsp;guys&nbsp;I&#39;m&nbsp;seeing&nbsp;something&nbsp;strange.&nbsp;It&nbsp;could&nbsp;totally&nbsp;be&nbsp;user&nbsp;error&nbsp;but&nbsp;I&nbsp;can&#39;t&nbsp;seem&nbsp;to&nbsp;figure&nbsp;it&nbsp;out.&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;am&nbsp;doing&nbsp;this&nbsp;on&nbsp;some&nbsp;tasks&nbsp;that&nbsp;I&nbsp;never&nbsp;await&nbsp;in&nbsp;order&nbsp;to&nbsp;get&nbsp;the&nbsp;exception:&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp;public&nbsp;static&nbsp;Task&nbsp;CatchUnhandledException(this&nbsp;Task&nbsp;task)&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp;{&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;return&nbsp;task.ContinueWith(continuation&nbsp;=&gt;&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Engine.UnhandledExceptionHandler(continuation.Exception),&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;TaskContinuationOptions.ExecuteSynchronously&nbsp;|&nbsp;TaskContinuationOptions.OnlyOnFaulted);&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp; &nbsp; &nbsp;}&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;and&nbsp;the&nbsp;Engine.UnhandledExceptionHandler&nbsp;just&nbsp;logs&nbsp;the&nbsp;exception.&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;What&#39;s&nbsp;strange&nbsp;is&nbsp;that&nbsp;the&nbsp;exception&nbsp;is&nbsp;null&nbsp;and&nbsp;also&nbsp;doing&nbsp;an Environment.StackTrace&nbsp;in&nbsp;the&nbsp;handler&nbsp;also&nbsp;yields&nbsp;nothing.&nbsp;I&nbsp;do&nbsp;have&nbsp;--debug&nbsp;with&nbsp;the&nbsp;mdb&nbsp;files&nbsp;so&nbsp;I&nbsp;would&nbsp;suspect&nbsp;to&nbsp;get&nbsp;the&nbsp;full&nbsp;stacktrace.&nbsp;I&nbsp;never&nbsp;saw&nbsp;this&nbsp;issue&nbsp;when&nbsp;I&nbsp;was&nbsp;running&nbsp;on&nbsp;.NET&nbsp;runtime&nbsp;but&nbsp;I&nbsp;also&nbsp;have&nbsp;added&nbsp;more&nbsp;async&nbsp;code&nbsp;since&nbsp;so&nbsp;I&#39;m&nbsp;not&nbsp;sure&nbsp;if&nbsp;it&#39;s&nbsp;something&nbsp;with&nbsp;Mono&nbsp;or&nbsp;my&nbsp;app.&nbsp;I&nbsp;just&nbsp;can&#39;t&nbsp;find&nbsp;anything&nbsp;online&nbsp;and&nbsp;the&nbsp;documentation&nbsp;for&nbsp;Tasks&nbsp;says&nbsp;that&nbsp;if&nbsp;it&#39;s&nbsp;faulted&nbsp;state&nbsp;there&nbsp;will&nbsp;be&nbsp;an&nbsp;exception.&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Regards&lt;/div&gt;--&nbsp;&lt;br&gt;Giuliano&nbsp;Barberi<br>
&lt;/div&gt;&lt;/div&gt;<br>

</tt>
