<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] patch for mono/jit/exception.c
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:linus%40linus.com">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="005502.html">
   <LINK REL="Next"  HREF="005508.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] patch for mono/jit/exception.c
   </H1>
    <B>Linus Upson
    </B> 
    <A HREF="mailto:linus%40linus.com"
       TITLE="[Mono-list] patch for mono/jit/exception.c">linus@linus.com
       </A><BR>
    <I>Sat, 4 May 2002 14:39:00 -0700</I>
    <P><UL>
        <LI> Previous message: <A HREF="005502.html">[Mono-list] patch for mono/jit/exception.c
</A></li>
        <LI> Next message: <A HREF="005508.html">[Mono-list] patch for mono/jit/exception.c
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5505">[ date ]</a>
              <a href="thread.html#5505">[ thread ]</a>
              <a href="subject.html#5505">[ subject ]</a>
              <a href="author.html#5505">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I forgot to include the small test program which demonstrates the
problem:

using System;

public class TryTest {
	public static void ThrowException() {
		throw new Exception();
	}

	public static void Main() {
		ThrowException();

		// If the following line is uncommented, mono will work
right.
		// Console.WriteLine(&quot;This shouldn't matter&quot;);

		try {
			Console.WriteLine(&quot;In try block&quot;);
		} catch (Exception e) {
			Console.WriteLine(&quot;------------------------&quot;);
			Console.WriteLine(e);
			Console.WriteLine(&quot;------------------------&quot;);
		}
	}
}

Before the patch, the Exception thrown in ThrowException() would be
caught by the catch block in Main().

Linus


-----Original Message-----
From: <A HREF="mailto:mono-list-admin@ximian.com">mono-list-admin@ximian.com</A> [mailto:<A HREF="mailto:mono-list-admin@ximian.com">mono-list-admin@ximian.com</A>] On
Behalf Of Linus Upson
Sent: Saturday, May 04, 2002 2:09 PM
To: <A HREF="mailto:mono-list@ximian.com">mono-list@ximian.com</A>
Subject: [Mono-list] patch for mono/jit/exception.c


Running NUnitConsole_mono.exe in mono on Windows exposed the following
bug:

If an exception were throw by the instruction immediately preceding a
try block, the exception would be considered to be thrown inside the try
block.

A patch is attached which appears to solve the problem. The patch won't
work if arch_handle_exception() can be called with ctx-&gt;SC_EIP pointing
to the instruction which threw the exception. I think an exception can
only be thrown by a CALL (as far as managed code is concerned) so EIP
will always point to the instruction after the CALL. If this isn't the
case, a different fix will be needed.

I believe the same problem exists on Linux as well, but I haven't
tested. 

Cheers,
Linus



</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="005502.html">[Mono-list] patch for mono/jit/exception.c
</A></li>
	<LI> Next message: <A HREF="005508.html">[Mono-list] patch for mono/jit/exception.c
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#5505">[ date ]</a>
              <a href="thread.html#5505">[ thread ]</a>
              <a href="subject.html#5505">[ subject ]</a>
              <a href="author.html#5505">[ author ]</a>
         </LI>
       </UL>
</body></html>
