<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-dev] SIGILL in finally clause without catch
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-dev%5D%20SIGILL%20in%20finally%20clause%20without%20catch&In-Reply-To=295e750a0804250401u5359a57egedecddea9aadce82%40mail.gmail.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="027649.html">
   <LINK REL="Next"  HREF="027653.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-dev] SIGILL in finally clause without catch</H1>
    <B>Christian St&#252;mpel</B> 
    <A HREF="mailto:mono-devel-list%40lists.ximian.com?Subject=%5BMono-dev%5D%20SIGILL%20in%20finally%20clause%20without%20catch&In-Reply-To=295e750a0804250401u5359a57egedecddea9aadce82%40mail.gmail.com"
       TITLE="[Mono-dev] SIGILL in finally clause without catch">mail at christian-stuempel.de
       </A><BR>
    <I>Fri Apr 25 07:51:10 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="027649.html">[Mono-dev] SIGILL in finally clause without catch
</A></li>
        <LI>Next message: <A HREF="027653.html">[Mono-dev] SIGILL in finally clause without catch
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#27652">[ date ]</a>
              <a href="thread.html#27652">[ thread ]</a>
              <a href="subject.html#27652">[ subject ]</a>
              <a href="author.html#27652">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi Zoltan,

&gt;<i> the (managed-to-native) wrapper. So the problem is usually in the  
</I>&gt;<i> native code.
</I>&gt;<i>
</I>But then why does introducing the &quot;catch&quot; and rethrowing resolve the  
matter?

platform is Mac OS X i386.

	Christian


Am 25.04.2008 um 12:01 schrieb Zoltan Varga:

&gt;<i>                                       Hi,
</I>&gt;<i>
</I>&gt;<i>   Mono throws that exception when it receives a SIGILL signal while
</I>&gt;<i> executing some
</I>&gt;<i> code. If it receives it while executing native code, it appears that
</I>&gt;<i> it is thrown by
</I>&gt;<i> the (managed-to-native) wrapper. So the problem is usually in the  
</I>&gt;<i> native code.
</I>&gt;<i>
</I>&gt;<i> What platform/os is this ?
</I>&gt;<i>
</I>&gt;<i>                Zoltan
</I>&gt;<i>
</I>&gt;<i> 2008/4/23 Christian St&#252;mpel &lt;<A HREF="http://lists.ximian.com/mailman/listinfo/mono-devel-list">mail at christian-stuempel.de</A>&gt;:
</I>&gt;&gt;<i> In code I have to port from MS .NET to mono I observed several SIGILL
</I>&gt;&gt;<i> crashes at points in code, where calls to external code are made  
</I>&gt;&gt;<i> within a
</I>&gt;&gt;<i> try block followed by a finally but *without* a catch statement.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  try {
</I>&gt;&gt;<i>  unrar.dosomething();
</I>&gt;&gt;<i>  throw new Exception(&quot;test&quot;);
</I>&gt;&gt;<i>  }
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  // no catch here
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  finally
</I>&gt;&gt;<i>  {
</I>&gt;&gt;<i>  unrar.close(); // calls unmanaged code
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  }
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The unmanaged code called in unrar.dosomething() is C++ code  
</I>&gt;&gt;<i> compiled with
</I>&gt;&gt;<i> exceptions enabled but it does not throw the exception, but the  
</I>&gt;&gt;<i> managed code
</I>&gt;&gt;<i> that follows. The call to unrar.close() (which does not throw any  
</I>&gt;&gt;<i> exception)
</I>&gt;&gt;<i> in the finally clause crashes with:
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> System.ExecutionEngineException: SIGILL  at (wrapper managed-to- 
</I>&gt;&gt;<i> native)
</I>&gt;&gt;<i> NntpApp.nntp.rar.Unrar:RARCloseArchive (intptr)  at
</I>&gt;&gt;<i> NntpApp.nntp.rar.Unrar.Close () [0x00000]   at
</I>&gt;&gt;<i> usenextapp.FilegroupPreview.ExtractFileFromRar (System.String path)
</I>&gt;&gt;<i> [0x00000]
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> The SIGILL does not appear if I catch the exception and rethrow it  
</I>&gt;&gt;<i> in the
</I>&gt;&gt;<i> finally clause
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  Exception e=null;
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  try {
</I>&gt;&gt;<i>  unmanaged1();
</I>&gt;&gt;<i>  throw new Exception(&quot;test&quot;);
</I>&gt;&gt;<i>  }
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  catch(Exception ex)
</I>&gt;&gt;<i>  {
</I>&gt;&gt;<i>  e= ex;
</I>&gt;&gt;<i>  }
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>  finally
</I>&gt;&gt;<i>  {
</I>&gt;&gt;<i>  cleanup();
</I>&gt;&gt;<i>  if (e!=null)
</I>&gt;&gt;<i>  throw e;
</I>&gt;&gt;<i>  }
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Any thoughts on that?
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Christian St&#252;mpel
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i>  Mono-devel-list mailing list
</I>&gt;&gt;<i>  <A HREF="http://lists.ximian.com/mailman/listinfo/mono-devel-list">Mono-devel-list at lists.ximian.com</A>
</I>&gt;&gt;<i>  <A HREF="http://lists.ximian.com/mailman/listinfo/mono-devel-list">http://lists.ximian.com/mailman/listinfo/mono-devel-list</A>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>
</PRE>















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="027649.html">[Mono-dev] SIGILL in finally clause without catch
</A></li>
	<LI>Next message: <A HREF="027653.html">[Mono-dev] SIGILL in finally clause without catch
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#27652">[ date ]</a>
              <a href="thread.html#27652">[ thread ]</a>
              <a href="subject.html#27652">[ subject ]</a>
              <a href="author.html#27652">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-devel-list">More information about the Mono-devel-list
mailing list</a><br>
</body></html>
