<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] Isolating exceptions between AppDomains
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-list%40lists.ximian.com?Subject=%5BMono-list%5D%20%3D%3Futf-8%3Fq%3FIsolating_exceptions_between_AppDomains%3F%3D&In-Reply-To=3d2f29dc0810230029o6f32bfc6i426bb50ec0bd911%40mail.gmail.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="039967.html">
   <LINK REL="Next"  HREF="039985.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] Isolating exceptions between AppDomains</H1>
    <B>paszczi</B> 
    <A HREF="mailto:mono-list%40lists.ximian.com?Subject=%5BMono-list%5D%20%3D%3Futf-8%3Fq%3FIsolating_exceptions_between_AppDomains%3F%3D&In-Reply-To=3d2f29dc0810230029o6f32bfc6i426bb50ec0bd911%40mail.gmail.com"
       TITLE="[Mono-list] Isolating exceptions between AppDomains">paszczi at go2.pl
       </A><BR>
    <I>Thu Oct 23 11:27:51 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="039967.html">[Mono-list] Isolating exceptions between AppDomains
</A></li>
        <LI>Next message: <A HREF="039985.html">[Mono-list] Isolating exceptions between AppDomains
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39975">[ date ]</a>
              <a href="thread.html#39975">[ thread ]</a>
              <a href="subject.html#39975">[ subject ]</a>
              <a href="author.html#39975">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
&gt;<i> On Wed, Oct 22, 2008 at 1:41 PM, paszczi  wrote:
</I>&gt;<i> &gt; I'm trying to build some software that uses plugins. The basic requirements is that when one plugins crashes (throws some exception), the whole system should recover from the error. So my first approach was to create AppDomain for each plugin and let it run there. However when plugins throws exception it goes back to default AppDomain and, as a result, crashes whole application. Is there any way to workaround this?
</I>&gt;<i> 
</I>&gt;<i> Use a try block.
</I>
OK, maybe I didn't clarify. Each plugins starts its own processing thread. So when the child thread throws exception there is no way to catch it in try-catch
</PRE>
















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="039967.html">[Mono-list] Isolating exceptions between AppDomains
</A></li>
	<LI>Next message: <A HREF="039985.html">[Mono-list] Isolating exceptions between AppDomains
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#39975">[ date ]</a>
              <a href="thread.html#39975">[ thread ]</a>
              <a href="subject.html#39975">[ subject ]</a>
              <a href="author.html#39975">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-list">More information about the Mono-list
mailing list</a><br>
</body></html>
